In [1]:
import math
import tqdm
import numpy as np
import pandas as pd

import pyarrow
import dask
import dask.array as da
import dask.bag as db
import dask.dataframe as dd
from dask.distributed import Client
# !pip install pyarrow==5.0 --user

In [2]:
n = 234994989
FRACTION = 1e-3
# FRACTION = 200000/n
SAMPLE_PICKLE = "quotebank-sample.pickle"
DATASET_PATH = "../quotebank"

In [3]:
client = Client()
client

In [4]:
quotebank_df_array = [dd.read_parquet(f"{DATASET_PATH}/quotes-{year}.parquet", engine="pyarrow") for year in range(2008, 2021)]
dataset = dd.concat(quotebank_df_array, interleave_partitions=True)
dataset.head()

,quoteID,quotation,speaker,qids,date,numOccurrences,urls,phase,speaker_prob,url_countries
0,2008-10-08-000029,10s of thousands of churches every week in the us,john mccain,Q10390,2008-10-08 14:12:13,1,[http://thenation.com/blogs/campaignmatters/36...,A,0.2767,[US]
1,2008-09-15-000037,"13th watered heavily up to the ridge, then roc...",gerry byrne,Multiple,2008-09-15 16:29:27,1,[http://belfasttelegraph.co.uk/sport/golf/amer...,A,0.4065,[UK]
2,2008-12-12-000046,"2 days in the valley,",None,None,2008-12-12 21:06:16,193,[http://netflixcinemajig.wordpress.com/2008/12...,A,0.2799,"[CA, IN, US, NZ, MY]"
3,2008-09-16-000159,80 per cent towards the basis of an agreement.,mario cossio,Q9029123,2008-09-16 01:12:16,2,[http://channelnewsasia.com/stories/afp_world/...,A,0.4073,[US]
4,2008-09-03-000269,"a challenge for the u.s. and the world,",None,None,2008-09-03 19:10:55,2,[http://warisboring.com/?p=1339],A,0.5239,[US]

In [ ]:
n = 234994989
# !date
# with pbar:
#     n = len(dataset)
#     print(n == 234994989)
#     print(n)
# !date

In [5]:
sample = dataset.sample(frac=FRACTION, replace=False).compute()
print(f"Sample length: {len(sample)}")

tornado.application - ERROR - Uncaught exception GET /status/ws (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8787', method='GET', uri='/status/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/rajic/.local/lib/python3.7/site-packages/tornado/websocket.py", line 954, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
  File "/home/rajic/.local/lib/python3.7/site-packages/tornado/web.py", line 3173, in wrapper
    return method(self, *args, **kwargs)
  File "/home/rajic/.local/lib/python3.7/site-packages/bokeh/server/views/ws.py", line 149, in open
    raise ProtocolError("Token is expired.")
bokeh.protocol.exceptions.ProtocolError: Token is expired.

Sample length: 234991

In [12]:
import pickle as pickle
with open(SAMPLE_PICKLE, 'wb') as f:
    pickle.dump(sample, f, protocol=pickle.HIGHEST_PROTOCOL)

In [ ]:
sample_2 = pd.read_pickle(SAMPLE_PICKLE)
sample_2.head()